[project]
name = "jcutils"
version = "0.7.4"
description = "python utils"
authors = [{ name = "lijc210", email = "lijc210@163.com" }]
readme = "README.md"
requires-python = ">= 3.9"
homepage = "https://github.com/lijic210/jcutils"
repository = "https://github.com/lijic210/jcutils"
documentation = "https://github.com/lijic210/jcutils"
keywords = ["utils", "toolkit", "tools", "python"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = { text = "MIT License" }

dependencies = [
    "python-dotenv",
    "pydantic",
    "requests",
    "python-dateutil",
    "httpx",
    "qiniu>=7.17.0",
]

[project.optional-dependencies]
# mysql相关
config = [
    "nacos-sdk-python>=2.0.11",
    "pyapollo-zenkilan>=0.2.0",
]

# mysql相关
mysql = [
    "PyMySQL",
    "aiomysql>=0.2.0",
    "DBUtils>=3.0.2",
]

# postgres相关
# psycopg在macOS M 芯片的依赖
# brew install libpq
postgresql = [
    "psycopg[pool]",
    "asyncpg>=0.30.0",
    "DBUtils>=3.0.2",
]

# sql server
# pymssql 在macOS M 芯片的依赖
# brew install freetds
# brew install openssl
pymssql = [
    "pymssql",
]


# Redis 相关
redis = [
    "redis>=3.5.3"]

# Kafka 相关
kafka = [
    "kafka-python",
]

# hdfs
hdfs = [
    "pyarrow>=12.0.0",
    "pyhdfs>=0.1.1",
]

# clickhouse
clickhouse = [
    "clickhouse-driver",
    "clickhouse_connect"
]

# 阿里云
alibabacloud = [
    "pyodps==0.11.6.1; python_version < '3.9'",
    "pyodps; python_version >= '3.9'",
    "alibabacloud-maxcompute20220104>=2.3.0",
    "alibabacloud_ecs20140526>=3.0.12",
    "alibabacloud_dataworks_public20200518>=4.7.2",
]

# 华为云
huaweicloud = [
    "huaweicloudsdkdli==3.1.19",
    "esdk-obs-python>=3.23.9.1",
]

# sentry
sentry = [
    "retry>=0.9.2",
]

# data
numpy = [
    "numpy>=1.21,<2; python_version < '3.9'",
    "numpy>=2; python_version >= '3.9'",
]

# elasticsearch
elasticsearch = [
    "elasticsearch>=8.10.0",
]

# 包含所有可选依赖
all = [
    "jcutils[config,mysql,postgresql,pymssql,redis,kafka,clickhouse,alibabacloud,huaweicloud,sentry,numpy,elasticsearch]",
]

[project.scripts]
jcutils = "jcutils:main"

[project.urls]
Homepage = "https://github.com/lijc210/jcutils"
Documentation = "https://github.com/lijic210/jcutils"
Source = "https://github.com/lijic210/jcutils"
Tracker = "https://github.com/lijc210/jcutils/issues"

[build-system]
requires = ["maturin>=1.2,<2.0"]
build-backend = "maturin"

managed = true
[tool.hatch.metadata]
allow-direct-references = true

[[tool.uv.index]]
url = "https://pypi.org/simple"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.uv.pip]
# index-url = "https://pypi.org/simple"
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[dependency-groups]
dev = ["requests>=2.32.3"]

[tool.uv]
python-install-mirror = "https://ghfast.top/https://github.com/indygreg/python-build-standalone/releases/download"
index-strategy = "unsafe-best-match" # uv 会在所有索引里找最高版本，而不是找到就停

[tool.maturin]
module-name = "jcutils._core"
python-packages = ["jcutils"]
python-source = "src"
